logger: 
  level: debug
  
http: 
  port: :8082

redis: 
  uri: "localhost:6379"

mongo:
  uri: "mongodb://user:password@localhost:27017"
  db: eduConnect
  connectTimeout: 10s

mongoCollections:
  users: users
  refreshTokens: refreshTokens
  s3: s3
  courses: courses

accessTokenExp: 3600s
refreshTokenExp: 86400s
publicKeyPath: "certs/jwtRSA256-public.pem"
privateKeyPath: "certs/jwtRSA256-private.pem"